sudo: required

# the new trusty images of Travis cause build errors with psycopg2, see https://github.com/travis-ci/travis-ci/issues/8897
dist: trusty
group: deprecated-2017Q4

language: python

python:
- '2.7'

env:
    - CKANVERSION=master
    - CKANVERSION=2.4
    - CKANVERSION=2.5

services:
    - redis-server
    - postgresql

install:
    - bash travis-build.bash

script: ./build.sh
